#!/bin/sh

. /etc/vtunerc.conf

test -f $DAEMON || exit 0

case "$1" in
    start)
        start-stop-daemon -S -b -m -p /var/run/vtunerc -x $DAEMON $OPTIONS
        ;;
    stop)
        start-stop-daemon -K -p /var/run/vtunerc
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

